### ISSUE TITLE
Violation of League recommendations

### ISSUE THREAD

**Issue by sagikazarmark** [thephpleague/DEPRECATED-squery#1]
The quality definition says code should be in src folder.

Some other things I noticed and seems to be weird (but only my 2 cents):
- composer.lock file is not ignored. IMO lock file should be ignored in libraries and should be kept only in deployed applications. This library will probably never be deployed as a standalone application.
- The clover file is manually removed in travis config. What's the reason behind that? IMO it is better to have as little configuration as possible. Removing that file manually does not make much sense, so it is rather noise in the config.
- In the editorconfig the indent size is set to 4 globally. I would recommend declaring a [_.php] and a [_.yml] glob pattern and setting sizes there (YAML uses 2 spaces in general, it is the official recommendation)

Also, you are the first using editorconfig, you could propose it to be a standard in the league.

Congrats for the package. ;)

**Comment by sagikazarmark** [comment]
@assertchris A real battle is happening right now:
https://github.com/thephpleague/tactician/pull/6

**Comment by philsturgeon** [comment]
That fight is HAWT.

Kill them composer.lock files through folks. Put them into deplorable applications but packages are no place for such things. 

https://philsturgeon.uk/php/2014/11/04/composer-its-almost-always-about-the-lock-file/

**Comment by assertchris** [comment]
You're a deplorable application! But seriously, this may as well be a discussion between tabs and spaces. Make a PSR or let package maintainers decide for themselves.

**Comment by sagikazarmark** [comment]
@philsturgeon I think it is not clear based on your blog post. But I agree with you.

**Comment by philsturgeon** [comment]
Tabs and spaces are pretty much arbitrary decisions without any real benefits either way. The presence of a composer.lock file has some real effects on the stability of the application and knock on effects for contributors and end users.   There is no one way to always do it, but the default should be "not present for packages" with it being added only if you really understand what you're doing - the use case provided in my article.  I doubt you want that. If this was internal code and we had full control of the envs it's being sent to then maybe,, but we aren't so we shouldn't.  You can ofc do as you like, I just want to be clear it's really not as arbitrary as tabs and spaces. :)    

---Sent from Boxer | http://getboxer.com

On 13 January 2015 08:39:09 GMT-5, Christopher Pitt <notifications@github.com> wrote:You're a deplorable application! But seriously, this may as well be a discussion between tabs and spaces. Make a PSR or let package maintainers decide for themselves.  —Reply to this email directly or view it on GitHub.

**Comment by assertchris** [comment]
My point was less about it being arbitrary and more about it being up to maintainers. Make it a rule or don't try to enforce it as a rule. It's not even mentioned on the List of Extraordinary Requirements™.

**Comment by philsturgeon** [comment]
I'm not enforcing anything I'm giving you advice.   

---Sent from Boxer | http://getboxer.com

On 13 January 2015 09:04:14 GMT-5, Christopher Pitt <notifications@github.com> wrote:My point was less about it being arbitrary and more about it being up to maintainers. Make it a rule or don't try to enforce it as a rule. It's not even mentioned on the List of Extraordinary Requirements™.  —Reply to this email directly or view it on GitHub.     =

**Comment by assertchris** [comment]
I appreciate it. [This doesn't help, though](https://twitter.com/philsturgeon/status/554993987229347840). And let's not forget this long-since closed issue is titled "Violation of League recommendations", though the lock file thing isn't yet a rule.

I know you're not saying it's a rule, and I am in complete agreement with you. Let's stop talking about it here. @sagikazarmark was cheeky to bring this up again, here...

**Comment by philsturgeon** [comment]
Oh! Yeah that puts your messages into better context.

You’ve been up a few more hours than me. :) 

Sturgeon Out!

**Comment by sagikazarmark** [comment]
@assertchris Sorry, I didn't mean to restart this shameful discussion we did long ago. Just wanted to point to the other one.
