### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by abshammeri** [thephpleague/DEPRECATED-squery#7]
The following dependency is missing:
     `"assertchris/simple-container": "~1.1.0"`

> Composer\Downloader\TransportException]
>   The "https://api.github.com/repos/assertchris/simple-container/zipball/cce1a8a3d39d825725fdc9b49c85c1ef00196e0d" file could not be
>    downloaded (HTTP/1.1 404 Not Found) 

Thanks,

**Comment by assertchris** [comment]
Apologies - it wasn't very clear. This library is deprecated. You're the first person to download it in months. :(

**Comment by abshammeri** [comment]
That's fine. Thanks ...
